# Generated by Django 3.2 on 2023-02-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230222_1504'),
        ('reviews', '0005_auto_20230222_1500'),
    ]

    operations = [
    ]
